sudo: false
branches:
  only:
  - master
language: node_js
node_js:
  - '8.11.3'
before_install:
  - npm i -g npm@5.6.0
install:
  - npm i npminstall && npminstall
before_script:
  - npm i -g gitbook-cli
script:
  - npm run build
after_script:
  - npminstall codecov && codecov
deploy:
  provider: pages
  local-dir: ./_book
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  slack:
    on_success: change